version: 1.{branch}.{build}

image: Visual Studio 2017

cache:
- c:\tools\vcpkg\installed
- boringssl -> boringssl-target.txt # we define the commit in here

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

init:

- cmd: ''

install:

- cmd: >-

    vcpkg install zlib:x64-windows-static

    vcpkg install libevent:x64-windows-static

    vcpkg install pcre:x64-windows-static

    vcpkg install getopt:x64-windows

    vcpkg integrate install
build_script:

- cmd: appveyor-windows.cmd

test_script:

- cmd: appveyor-windows-test.cmd
