version: 1.{branch}.{build}

image: Visual Studio 2017

cache:
- c:\tools\vcpkg -> appveyor-windows.yml,appveyor-update-vcpkg.cmd,c:\tools\vcpkg\.git\refs\heads\master
- boringssl -> appveyor-windows.cmd,boringssl-target.txt # we define the commit in here

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  VCPKG_DISABLE_METRICS: true

init:

- cmd: ''

install:

- cmd: >-

    call appveyor-update-vcpkg.cmd

    vcpkg install zlib:x64-windows-static

    vcpkg install libevent:x64-windows-static

    vcpkg install pcre2:x64-windows-static

    vcpkg install getopt:x64-windows

    vcpkg integrate install

build_script:

- cmd: appveyor-windows.cmd

test_script:

- cmd: appveyor-windows-test.cmd

